#!/bin/bash

wget -q --tries=10 --timeout=20 --spider http://google.com
if [[ $? -eq 0 ]]; then
        #echo "Online"
else
        echo "%(date) No Internet Connection"
        tmux kill-session -t nac-auth
        ./phantom.start
fi
